#!/bin/sh

echo "===== Running pre-commit ====="
echo "===== pre-commit: running pytest ====="

# pytest

if [ $? -ne 0 ]
then
  echo "==== pre-commit: tests failed, aborting ===="
  exit 1
fi

echo "==== pre-commit: updating version file ===="

version_path="/src/mediascraper/version.py"
full_path="${PWD}${version_path}"

python $full_path


echo "==== pre-commit: success! ===="